theme: starter-academic
title: Rozum S, UXR
baseurl: ''
copyright: '{year}'
enableGitInfo: no
defaultContentLanguage: en
hasCJKLanguage: no
removePathAccents: yes
summaryLength: 30
enableEmoji: yes
enableRobotsTXT: yes
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  authors: /author/:slug/
  categories: /category/:slug/
  event: /talk/:slug/
  publication_types: /publication-type/:slug/
  tags: /tag/:slug/
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
    - headers
  section:
    - HTML
    - RSS
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
  tableOfContents:
    endLevel: 3
    startLevel: 2
imaging:
  anchor: smart
  quality: 75
  resampleFilter: lanczos
taxonomies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags
related:
  includeNewer: yes
  indices:
    - name: title
      weight: 60
    - name: summary
      weight: 50
    - name: tags
      weight: 80
    - name: categories
      weight: 70
  threshold: 80
  toLower: yes
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/netlify-cms-academic
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy
defaultContentLanguageInSubdir: true
languages:
  ru:
    contentDir: content/ru
    disabled: false
    languageCode: ru
    languageDirection: ltr
    languageName: Russian
    weight: 0
  en:
    contentDir: content/en
    disabled: false
    languageCode: en-US
    languageDirection: ltr
    languageName: English
